
title: My Resume
url: 'http://akashmantry.github.io'
baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Akash Mantry
tagline: Full Stack Developer
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: amantry@umass.edu
phone: 413 437 4525
website: blogwithakash.appspot.com/ #do not add http://
linkedin: akash-mantry-64631069/
github: akashmantry


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
